version: "3"

services:
  api:
    image: dok_fe
    container_name: dok_fe
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
