name: GitHub Actions CI/CD Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Copy all sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-
      - name: Install, build, test
        run: |
          npm ci
          npm run build
          npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   env:
      #     CI: true
      # - name: Build the tagged Docker image
      #   run: docker build -f .docker/dok.fe.Dockerfile -t dok_fe .
      # - name: Deploy on heroku
      #   id: heroku
      #   uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
      #   with:
      #     email: ${{ secrets.HEROKU_EMAIL }}
      #     api_key: ${{ secrets.HEROKU_API_KEY }}
      #     docker_compose_file: ".docker/docker-compose.yml"
      #     heroku_apps: '[{"imagename":"dok_fe","appname":"heroku-fresh","apptype":"web"}]'
